language: python

sudo: false

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27-flake8
    - python: 3.8
      env: TOXENV=py38-flake8
    - python: 3.7
      env: TOXENV=precommit
    - python: 3.7
      env: TOXENV=safety
    - python: 3.7
      env: TOXENV=mypy
    - python: 3.7
      env: TOXENV=compile-catalog
    - python: 2.7
      env: TOXENV=py27-dj111
    - python: 3.5
      env: TOXENV=py35-dj111
    - python: 3.5
      env: TOXENV=py35-dj21
    - python: 3.6
      env: TOXENV=py36-dj111
    - python: 3.6
      env: TOXENV=py36-dj21
    - python: 3.6
      env: TOXENV=py36-djmaster
    - python: 3.7
      env: TOXENV=py37-dj21
    - python: 3.7
      env: TOXENV=py37-dj22
    - python: 3.8
      env: TOXENV=py38-dj22
    - python: 3.7
      env: TOXENV=py37-dj30
    - python: 3.8
      env: TOXENV=py38-dj30
    - python: 3.7
      env: TOXENV=py37-dj22-postgres
      services:
        - postgresql
    - python: 3.8
      env: TOXENV=py38-dj22-postgres
      services:
        - postgresql
    - python: 3.7
      env: TOXENV=py37-dj30-postgres
      services:
        - postgresql
    - python: 3.8
      env: TOXENV=py38-dj30-postgres
      services:
        - postgresql
    - python: 3.7
      env: TOXENV=py37-dj22-mysql
      services:
        - mysql
    - python: 3.8
      env: TOXENV=py38-dj22-mysql
      services:
        - mysql
    - python: 3.7
      env: TOXENV=py37-dj30-mysql
      services:
        - mysql
    - python: 3.8
      env: TOXENV=py38-dj30-mysql
      services:
        - mysql
    - python: 3.7
      env: TOXENV=py37-djmaster
    - python: 3.8
      env: TOXENV=py38-djmaster
    - python: 3.7
      env: TOXENV=py37-djmaster-postgres
      services:
        - postgresql
    - python: 3.8
      env: TOXENV=py38-djmaster-postgres
      services:
        - postgresql
    - python: pypy
      env: TOXENV=pypy-dj111
    - python: pypy3
      env: TOXENV=pypy3-dj111
    - python: pypy3
      env: TOXENV=pypy3-dj20
    - python: pypy3
      env: TOXENV=pypy3-dj21
    - python: pypy3
      env: TOXENV=pypy3-djmaster

  allow_failures:
    - python: 3.6
      env: TOXENV=py36-djmaster
    - python: 3.7
      env: TOXENV=py37-djmaster
    - python: 3.8
      env: TOXENV=py38-djmaster
    - python: 3.7
      env: TOXENV=py37-djmaster-postgres
    - python: 3.8
      env: TOXENV=py38-djmaster-postgres
    - python: pypy3
      env: TOXENV=pypy3-djmaster
    - python: pypy
      env: TOXENV=pypy-dj111

install:
  - pip install virtualenv tox coveralls

script:
  - tox

after_success:
  - coveralls
